version: '3.8'
services:
  php:
    container_name: ll_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    env_file:
      - .env.local
    # This statement is used to tell the service that it will have to use the user with uid 1000 and gid 1000 internally.
    # In most cases, the user we use on our local machine is the user with uid 1000 and gid 1000.
    user: 1000:1000
  language_mysql:
    image: mysql:8.0
    container_name: ll_db
    restart: on-failure

    volumes:
      - ll_db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env.local
    ports:
      - "3342:3306"
  nginx:
    image: nginx:1.15.3-alpine
    container_name: ll_web
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    ports:
      - 8057:80

  test_php:
    container_name: test_ll_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    env_file:
      - .env.local
    # This statement is used to tell the service that it will have to use the user with uid 1000 and gid 1000 internally.
    # In most cases, the user we use on our local machine is the user with uid 1000 and gid 1000.
    user: 1000:1000
  test_language_mysql:
    image: mysql:8.0
    container_name: test_ll_db
    restart: on-failure

    volumes:
      - test_ll_db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env.test
    ports:
      - "3343:3306"
  test_nginx:
    image: nginx:1.15.3-alpine
    container_name: test_ll_web
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    ports:
      - 8091:80
volumes:
  ll_db:
