version:  '3.3'
services:
  php:
    container_name: language_learning
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    env_file:
      - .env
    # This statement is used to tell the service that it will have to use the user with uid 1000 and gid 1000 internally.
    # In most cases, the user we use on our local machine is the user with uid 1000 and gid 1000.
    user: 1000:1000
  language_mysql:
    image: mysql:8.0
    container_name: language_learning_db_container
    restart: on-failure

    volumes:
      - language_learning_db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    env_file:
      - .env
    ports:
      - "3307:3306"
  nginx:
    image: nginx:1.15.3-alpine
    container_name: expelliar_web_container
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    ports:
      - 8091:80
volumes:
  language_learning_db: